#ifndef TEMP_CTNTROL_H
#define TEMP_CTNTROL_H

enum eDISPLAY_MODE
{
	DISPLAY_MODE_TEMPERATURE=0,
	DISPLAY_MODE_TEMPERATURE_SET1,
	DISPLAY_MODE_TEMPERATURE_SET2,
};


#define DELTA_TEMPERATURE 10 // unit:0.1 degree


#endif //TEMP_CTNTROL_H